# Generated by Django 5.2.11 on 2026-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text='User-provided symptom description')),
                ('predicted_disease', models.CharField(max_length=255)),
                ('confidence', models.FloatField(help_text='Prediction confidence percentage')),
                ('risk_level', models.CharField(max_length=50)),
                ('is_emergency', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Prediction Log',
                'verbose_name_plural': 'Prediction Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
